#:schema node_modules/wrangler/config-schema.json
name = "contestone-app"
compatibility_date = "2024-11-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "contestone-db"
database_id = "REPLACE_WITH_YOUR_D1_DATABASE_ID"
